
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-08
owner: ucsb-cs156-s25
repo_name: team01-s25-08
pull_requests: [{"author":{"id":"U_kgDOCM7nFQ","is_bot":false,"login":"rbuneti","name":""},"headRefName":"rb-recreq-get-by-id","number":68,"title":"Rb - add get by id for recreq","url":"https://github.com/ucsb-cs156-s25/team01-s25-08/pull/68"},{"author":{"id":"U_kgDOCM7nFQ","is_bot":false,"login":"rbuneti","name":""},"headRefName":"rb-create-recreq-controller-fix","number":65,"title":"Rb create recreq controller fix","url":"https://github.com/ucsb-cs156-s25/team01-s25-08/pull/65"},{"author":{"id":"U_kgDOCM7nFQ","is_bot":false,"login":"rbuneti","name":""},"headRefName":"rbuneti-recreqtable","number":63,"title":"Rbuneti recreqtable","url":"https://github.com/ucsb-cs156-s25/team01-s25-08/pull/63"}]
