
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-08
owner: ucsb-cs156-s25
repo_name: team01-s25-08
pull_requests: [{"author":{"id":"U_kgDOB7-7uA","is_bot":false,"login":"selenazeng1","name":"Selena Zeng"},"headRefName":"sz-Articles-add-GET","number":53,"title":"add GET endpoint","url":"https://github.com/ucsb-cs156-s25/team01-s25-08/pull/53"},{"author":{"id":"U_kgDOCu9O7Q","is_bot":false,"login":"nathanalexander626","name":"Nathan Alexander"},"headRefName":"NA-HelpRequest-add-controller-put","number":52,"title":"NA-HelpRequest-add-controller-put","url":"https://github.com/ucsb-cs156-s25/team01-s25-08/pull/52"}]
