
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-08
owner: ucsb-cs156-s25
repo_name: team01-s25-08
pull_requests: [{"author":{"id":"U_kgDOB0zlvA","is_bot":false,"login":"tiffanyxgu","name":""},"headRefName":"Tiffany-MenuItemRequest","number":48,"title":"Create database table for MenuItemReview","url":"https://github.com/ucsb-cs156-s25/team01-s25-08/pull/48"},{"author":{"id":"U_kgDOCu9O7Q","is_bot":false,"login":"nathanalexander626","name":"Nathan Alexander"},"headRefName":"NA-HelpRequest-createController-db","number":47,"title":"Creating helprequest controller with tests and fixing database structure","url":"https://github.com/ucsb-cs156-s25/team01-s25-08/pull/47"},{"author":{"id":"MDQ6VXNlcjgwNjE0Mzg1","is_bot":false,"login":"giozucca","name":""},"headRefName":"gl-UCSBDiningCommonsMenuItem-create-db","number":46,"title":"Create database table for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s25/team01-s25-08/pull/46"},{"author":{"id":"U_kgDOB96_2w","is_bot":false,"login":"hannuhsu","name":"Hannah Su"},"headRefName":"Hannah-ReqRequestTable","number":44,"title":"Create database table for UCSBOrganization","url":"https://github.com/ucsb-cs156-s25/team01-s25-08/pull/44"}]
