
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-08
owner: ucsb-cs156-s25
repo_name: team01-s25-08
pull_requests: [{"author":{"id":"MDQ6VXNlcjgwNjE0Mzg1","is_bot":false,"login":"giozucca","name":""},"headRefName":"gl-UCSBDiningCommonsController","number":57,"title":"Add UCSBDiningCommonsMenuItemController with authorization and tests","url":"https://github.com/ucsb-cs156-s25/team01-s25-08/pull/57"},{"author":{"id":"U_kgDOB96_2w","is_bot":false,"login":"hannuhsu","name":"Hannah Su"},"headRefName":"Hannah-ReqRequestTable","number":56,"title":"Create UCSBOrganizationController, add GET (index) and POST (create)","url":"https://github.com/ucsb-cs156-s25/team01-s25-08/pull/56"},{"author":{"id":"U_kgDOB7-7uA","is_bot":false,"login":"selenazeng1","name":"Selena Zeng"},"headRefName":"sz-Articles-add-DELETE","number":55,"title":"Sz - Add DELETE endpoint for Articles","url":"https://github.com/ucsb-cs156-s25/team01-s25-08/pull/55"}]
