
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-08
owner: ucsb-cs156-s25
repo_name: team01-s25-08
pull_requests: [{"author":{"id":"MDQ6VXNlcjgwNjE0Mzg1","is_bot":false,"login":"giozucca","name":""},"headRefName":"gl-UCSBDiningCommonsMenuItem-item_by_id","number":62,"title":"Add get ucsb dining commons menu item by ID","url":"https://github.com/ucsb-cs156-s25/team01-s25-08/pull/62"},{"author":{"id":"U_kgDOB0zlvA","is_bot":false,"login":"tiffanyxgu","name":""},"headRefName":"tg-MenuItemReview-controller-delete","number":61,"title":"tg - added delete endpoint and tests for MenuItemReview","url":"https://github.com/ucsb-cs156-s25/team01-s25-08/pull/61"}]
